Repository ucsb-cs156-w24/proj-organic-w24-6pm-1, pull requests merged in 2024-03, with the labels that each got.

#40 PL - Bug fix footer
  frontend/src/main/components/Nav/Footer.js
  frontend/src/tests/components/Nav/Footer.test.js
Labels: FIXME - Peer CR

#41 PL - Icon bug fix
  frontend/public/favicon.ico
  frontend/public/logo192.png
  frontend/public/logo512.png
Labels: 5

#67 sk - added popup warning
  frontend/src/main/components/Users/UsersTable.js
  frontend/src/tests/components/Users/UsersTable.test.js
  frontend/src/tests/pages/AdminUsersPage.test.js
Labels: 10

#70 sk - [Feature] gave the website a look over.
  frontend/src/main/components/Users/UsersTable.js
  frontend/src/main/pages/HomePage.js
  frontend/src/main/pages/LoginPage.js
  frontend/src/main/pages/NotFoundPage.js
  frontend/src/main/pages/css/LoginPage.css
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/components/Users/UsersTable.test.js
  frontend/src/tests/pages/HomePage.test.js
  frontend/src/tests/pages/NotFoundPage.test.js
Labels: 15

#57 Jenil add entity and repository class for schools table
  src/main/java/edu/ucsb/cs156/organic/entities/School.java
  src/main/java/edu/ucsb/cs156/organic/repositories/SchoolRepository.java
  src/test/java/edu/ucsb/cs156/organic/entities/SchoolTests.java
Labels: 5

#43 sk - added [FEATURE]: Instructors can create, edit and delete courses
  frontend/src/main/pages/CourseIndexPage.js
  frontend/src/main/pages/HomePage.js
  frontend/src/tests/pages/CourseIndexPage.test.js
  src/main/java/edu/ucsb/cs156/organic/controllers/CoursesController.java
  src/main/java/edu/ucsb/cs156/organic/entities/User.java
  src/test/java/edu/ucsb/cs156/organic/Interceptors/RoleUserInterceptorTests.java
  src/test/java/edu/ucsb/cs156/organic/controllers/CoursesControllerTests.java
Labels: 10

#54 sb - fixed bug where course can end before it starts
  frontend/src/main/components/Courses/CoursesForm.js
  frontend/src/main/components/Courses/dateValidation.js
  frontend/src/main/pages/CoursesCreatePage.js
  frontend/src/main/pages/CoursesEditPage.js
  frontend/src/tests/components/Courses/CoursesForm.test.js
  frontend/src/tests/components/Courses/dateValidation.test.js
  frontend/src/tests/pages/CoursesEditPage.test.js
Labels: 5

#47 sk - resolved [BUG]: Last Online in User Profile Defaults to Wrong Date
  src/main/java/edu/ucsb/cs156/organic/Interceptors/RoleUserInterceptorAppConfig.java
  src/main/java/edu/ucsb/cs156/organic/controllers/UserInfoController.java
  src/main/java/edu/ucsb/cs156/organic/entities/Course.java
  src/main/java/edu/ucsb/cs156/organic/entities/User.java
  src/test/java/edu/ucsb/cs156/organic/Interceptors/RoleUserInterceptorTests.java
  src/test/java/edu/ucsb/cs156/organic/controllers/UserInfoControllerTests.java
  src/test/java/edu/ucsb/cs156/organic/testconfig/MockCurrentUserServiceImpl.java
Labels: 5, FIXME - Peer CR

#58 sk - [Feature] added staff button. in addition to a table component, fixtures and storybook.
  frontend/src/fixtures/staffFixture.js
  frontend/src/main/components/Courses/CoursesTable.js
  frontend/src/main/components/Staff/StaffTable.js
  frontend/src/main/components/Utils/StaffUtils.js
  frontend/src/stories/components/Staff/StaffTable.stories.js
  frontend/src/tests/components/Courses/CoursesTable.test.js
  frontend/src/tests/components/Staff/StaffTable.test.js
  frontend/src/tests/components/Utils/StaffUtils.test.js
Labels: 15

#52 sk - added [Feature] join for normal user
  frontend/src/App.js
  frontend/src/main/components/Courses/CoursesTable.js
  frontend/src/main/components/Users/UsersTable.js
  frontend/src/tests/components/Courses/CoursesTable.test.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/components/Users/UsersTable.test.js
  src/test/java/edu/ucsb/cs156/organic/Interceptors/RoleUserInterceptorTests.java
Labels: 5

#56 sk - [Feature] developer can use unlimited colors for buttons
  frontend/src/main/components/OurTable.js
  frontend/src/tests/components/OurTable.test.js
  src/test/java/edu/ucsb/cs156/organic/Interceptors/RoleUserInterceptorTests.java
Labels: 10, FIXME - Peer CR

#64 sb - [Feature] added total courses counter to course table
  frontend/src/main/components/Courses/CoursesTable.js
  frontend/src/tests/components/Courses/CoursesTable.test.js
Labels: 5

#61 Victor school post dev
  src/main/java/edu/ucsb/cs156/organic/controllers/SchoolController.java
  src/main/java/edu/ucsb/cs156/organic/entities/School.java
  src/main/java/edu/ucsb/cs156/organic/repositories/SchoolRepository.java
  src/main/resources/db/migration/changes/0007_CreateSchoolTable.json
  src/test/java/edu/ucsb/cs156/organic/controllers/SchoolControllerTests.java
Labels: 15

#60 Victor school delete dev
  src/main/java/edu/ucsb/cs156/organic/controllers/SchoolController.java
  src/main/java/edu/ucsb/cs156/organic/repositories/SchoolRepository.java
  src/test/java/edu/ucsb/cs156/organic/Interceptors/RoleUserInterceptorTests.java
  src/test/java/edu/ucsb/cs156/organic/controllers/SchoolControllerTests.java
Labels: 10

#62 Victor school put dev
  src/main/java/edu/ucsb/cs156/organic/controllers/SchoolController.java
  src/main/java/edu/ucsb/cs156/organic/repositories/SchoolRepository.java
  src/test/java/edu/ucsb/cs156/organic/controllers/SchoolControllerTests.java
Labels: 10

#73 Jenil school get one and get all
  frontend/src/main/components/School/SchoolTable.js
  frontend/src/main/components/Utils/SchoolUtils.js
  frontend/src/tests/components/School/SchoolTable.test.js
  frontend/src/tests/components/Utils/SchoolUtils.test.js
  src/main/java/edu/ucsb/cs156/organic/controllers/SchoolController.java
  src/main/java/edu/ucsb/cs156/organic/repositories/SchoolRepository.java
  src/test/java/edu/ucsb/cs156/organic/controllers/SchoolControllerTests.java
Labels: 15

#68 Victor school table and school utils component in addition to the storybook.
  frontend/src/stories/components/School/SchoolTable.stories.js
  src/test/java/edu/ucsb/cs156/organic/controllers/SchoolControllerTests.java
Labels: 5

#74 Victor school index page dev
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/SchoolIndexPage.js
  frontend/src/tests/pages/SchoolIndexPage.test.js
  src/main/java/edu/ucsb/cs156/organic/controllers/SchoolController.java
  src/main/java/edu/ucsb/cs156/organic/repositories/SchoolRepository.java
  src/test/java/edu/ucsb/cs156/organic/controllers/SchoolControllerTests.java
Labels: 10
